# Generated by Django 5.1.3 on 2024-12-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peltloader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='entry1',
            new_name='Body_Number',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='entry2',
            new_name='Date',
        ),
    ]
